In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [3]:
df = pd.read_csv("all_matches_games_ids.csv")

df.head()

,Tournament,Tournament ID,Stage,Stage ID,Match Type,Match Type ID,Match Name,Match ID,Map,Game ID,Year
0,Valorant Champions 2021,449,Group Stage,945,Opening (D),8272.0,Vision Strikers vs FULL SENSE,51282,Haven,57948.0,2021
1,Valorant Champions 2021,449,Group Stage,945,Opening (D),8272.0,Vision Strikers vs FULL SENSE,51282,Breeze,57949.0,2021
2,Valorant Champions 2021,449,Group Stage,945,Opening (C),8268.0,Team Vikings vs Crazy Raccoon,51278,Icebox,57936.0,2021
3,Valorant Champions 2021,449,Group Stage,945,Opening (C),8268.0,Team Vikings vs Crazy Raccoon,51278,Haven,57937.0,2021
4,Valorant Champions 2021,449,Group Stage,945,Opening (D),8272.0,FNATIC vs Cloud9,51283,Icebox,57951.0,2021

In [4]:
df.shape

(27450, 11)

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 27450 entries, 0 to 27449
Data columns (total 11 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Tournament     27450 non-null  object
 1   Tournament ID  27450 non-null  int64
 2   Stage          27450 non-null  object
 3   Stage ID       27450 non-null  int64
 4   Match Type     27450 non-null  object
 5   Match Type ID  27375 non-null  float64
 6   Match Name     27450 non-null  object
 7   Match ID       27450 non-null  int64
 8   Map            27448 non-null  object
 9   Game ID        27449 non-null  float64
 10  Year           27450 non-null  int64
dtypes: float64(2), int64(4), object(5)
memory usage: 2.3+ MB

In [7]:
df.columns

Index(['Tournament', 'Tournament ID', 'Stage', 'Stage ID', 'Match Type',
       'Match Type ID', 'Match Name', 'Match ID', 'Map', 'Game ID', 'Year'],
      dtype='object')

In [8]:
df.head()

,Tournament,Tournament ID,Stage,Stage ID,Match Type,Match Type ID,Match Name,Match ID,Map,Game ID,Year
0,Valorant Champions 2021,449,Group Stage,945,Opening (D),8272.0,Vision Strikers vs FULL SENSE,51282,Haven,57948.0,2021
1,Valorant Champions 2021,449,Group Stage,945,Opening (D),8272.0,Vision Strikers vs FULL SENSE,51282,Breeze,57949.0,2021
2,Valorant Champions 2021,449,Group Stage,945,Opening (C),8268.0,Team Vikings vs Crazy Raccoon,51278,Icebox,57936.0,2021
3,Valorant Champions 2021,449,Group Stage,945,Opening (C),8268.0,Team Vikings vs Crazy Raccoon,51278,Haven,57937.0,2021
4,Valorant Champions 2021,449,Group Stage,945,Opening (D),8272.0,FNATIC vs Cloud9,51283,Icebox,57951.0,2021

In [9]:
df.shape

(27450, 11)

In [10]:
df.isnull().sum()

Tournament        0
Tournament ID     0
Stage             0
Stage ID          0
Match Type        0
Match Type ID    75
Match Name        0
Match ID          0
Map               2
Game ID           1
Year              0
dtype: int64

In [11]:
df.columns.tolist()

['Tournament',
 'Tournament ID',
 'Stage',
 'Stage ID',
 'Match Type',
 'Match Type ID',
 'Match Name',
 'Match ID',
 'Map',
 'Game ID',
 'Year']

In [12]:
df.tail()

,Tournament,Tournament ID,Stage,Stage ID,Match Type,Match Type ID,Match Name,Match ID,Map,Game ID,Year
27445,VCT 2026: China Kickoff,2685,Main Event,0,Middle Final,35570.0,Xi Lai Gaming vs Bilibili Gaming,598941,Split,245264.0,2026
27446,VCT 2026: China Kickoff,2685,Main Event,0,Lower Final,35576.0,Bilibili Gaming vs EDward Gaming,598950,Pearl,245289.0,2026
27447,VCT 2026: China Kickoff,2685,Main Event,0,Lower Final,35576.0,Bilibili Gaming vs EDward Gaming,598950,Haven,245290.0,2026
27448,VCT 2026: China Kickoff,2685,Main Event,0,Lower Final,35576.0,Bilibili Gaming vs EDward Gaming,598950,Abyss,245291.0,2026
27449,VCT 2026: China Kickoff,2685,Main Event,0,Lower Final,35576.0,Bilibili Gaming vs EDward Gaming,598950,Split,253654.0,2026

In [13]:
df_teams = pd.read_csv("all_teams_mapping.csv")

df_teams.head()

  Abbreviated        Full Name
0          VS  Vision Strikers
1          FS       FULL SENSE
2         VKS     Team Vikings
3          CR  Carleton Ravens
4         FNC           FNATIC

In [14]:
df_teams.columns.tolist()

['Abbreviated', 'Full Name']

In [15]:
df_team_ids = pd.read_csv("all_teams_ids.csv")

df_team_ids.head()

              Team  Team ID
0  Vision Strikers    198.0
1       FULL SENSE   4050.0
2     Team Vikings    420.0
3    Crazy Raccoon    277.0
4           FNATIC   2593.0

In [17]:
df_tournaments = pd.read_csv("all_tournaments_stages_match_types_ids.csv")

df_tournaments.head()

,Tournament,Tournament ID,Stage,Stage ID,Match Type,Match Type ID,Year
0,Champions Tour Asia-Pacific: Last Chance Quali...,560,All Stages,NaN,All Match Types,NaN,2021
1,Champions Tour Asia-Pacific: Last Chance Quali...,560,Main Event,1096.0,Upper Round 1,NaN,2021
2,Champions Tour Asia-Pacific: Last Chance Quali...,560,Main Event,1096.0,Grand Final,7577.0,2021
3,Champions Tour Asia-Pacific: Last Chance Quali...,560,Main Event,1096.0,Lower Bracket Final,7576.0,2021
4,Champions Tour Asia-Pacific: Last Chance Quali...,560,Main Event,1096.0,Lower Bracket Round 1,7572.0,2021

In [18]:
df_tournaments.columns.tolist()

['Tournament',
 'Tournament ID',
 'Stage',
 'Stage ID',
 'Match Type',
 'Match Type ID',
 'Year']

In [25]:
import os

for root, dirs, files in os.walk("."):
    for file in files:
        if file.endswith(".csv"):
            print(os.path.join(root, file))

.\all_matches_games_ids.csv
.\all_players_ids.csv
.\all_teams_ids.csv
.\all_teams_mapping.csv
.\all_tournaments_stages_match_types_ids.csv
.\.ipynb_checkpoints\all_matches_games_ids-checkpoint.csv
.\.ipynb_checkpoints\all_players_ids-checkpoint.csv
.\.ipynb_checkpoints\all_tournaments_stages_match_types_ids-checkpoint.csv

In [21]:
df_players = pd.read_csv("all_players_ids.csv")

df_players.head()

  Player  Player ID
0   MaKo     4462.0
1   stax      485.0
2     Rb      488.0
3   k1Ng      771.0
4   BuZz      804.0

In [24]:
df_tournaments.head()

,Tournament,Tournament ID,Stage,Stage ID,Match Type,Match Type ID,Year
0,Champions Tour Asia-Pacific: Last Chance Quali...,560,All Stages,NaN,All Match Types,NaN,2021
1,Champions Tour Asia-Pacific: Last Chance Quali...,560,Main Event,1096.0,Upper Round 1,NaN,2021
2,Champions Tour Asia-Pacific: Last Chance Quali...,560,Main Event,1096.0,Grand Final,7577.0,2021
3,Champions Tour Asia-Pacific: Last Chance Quali...,560,Main Event,1096.0,Lower Bracket Final,7576.0,2021
4,Champions Tour Asia-Pacific: Last Chance Quali...,560,Main Event,1096.0,Lower Bracket Round 1,7572.0,2021

In [26]:
df_scores_2025 = pd.read_csv("maps_scores.csv")
df_scores_2025.head()

,Tournament,Stage,Match Type,Match Name,Map,Team A,Team A Score,Team A Attacker Score,Team A Defender Score,Team A Overtime Score,Team B,Team B Score,Team B Attacker Score,Team B Defender Score,Team B Overtime Score,Duration
0,Valorant Champions 2025,Group Stage,Opening (A),Paper Rex vs Xi Lai Gaming,Bind,Paper Rex,13,6,7,NaN,Xi Lai Gaming,9,3,6,NaN,48:56
1,Valorant Champions 2025,Group Stage,Opening (A),Paper Rex vs Xi Lai Gaming,Sunset,Paper Rex,13,8,5,NaN,Xi Lai Gaming,5,1,4,NaN,39:04
2,Valorant Champions 2025,Group Stage,Opening (A),GIANTX vs Sentinels,Corrode,GIANTX,6,6,0,NaN,Sentinels,13,7,6,NaN,41:17
3,Valorant Champions 2025,Group Stage,Opening (A),GIANTX vs Sentinels,Sunset,GIANTX,13,10,3,NaN,Sentinels,4,2,2,NaN,38:15
4,Valorant Champions 2025,Group Stage,Opening (A),GIANTX vs Sentinels,Haven,GIANTX,13,4,9,NaN,Sentinels,9,1,8,NaN,51:34

In [27]:
df_scores_2025.shape

(1277, 16)

In [28]:
df_scores_2025.isnull().sum()

Tournament                  0
Stage                       0
Match Type                  0
Match Name                  0
Map                         0
Team A                      0
Team A Score                0
Team A Attacker Score       0
Team A Defender Score       0
Team A Overtime Score    1132
Team B                      0
Team B Score                0
Team B Attacker Score       0
Team B Defender Score       0
Team B Overtime Score    1132
Duration                   98
dtype: int64

In [29]:
(df_scores_2025["Team A Score"] == df_scores_2025["Team B Score"]).sum()

np.int64(0)

In [34]:
df_scores_2025["Winner"] = np.where(
    df_scores_2025["Team A Score"] > df_scores_2025["Team B Score"],
    df_scores_2025["Team A"],
    df_scores_2025["Team B"]
)
df_scores_2025[["Team A", "Team A Score", "Team B", "Team B Score", "Winner"]].head()

      Team A  Team A Score         Team B  Team B Score     Winner
0  Paper Rex            13  Xi Lai Gaming             9  Paper Rex
1  Paper Rex            13  Xi Lai Gaming             5  Paper Rex
2     GIANTX             6      Sentinels            13  Sentinels
3     GIANTX            13      Sentinels             4     GIANTX
4     GIANTX            13      Sentinels             9     GIANTX

In [35]:
df_scores_2025["Team A Win"] = (df_scores_2025["Team A Score"] > df_scores_2025["Team B Score"]).astype(int)
df_scores_2025["Team A Win"].value_counts()

Team A Win
1    652
0    625
Name: count, dtype: int64

In [36]:
features = ["Tournament", "Stage", "Match Type", "Map", "Team A", "Team B"]
X = df_scores_2025[features]
y = df_scores_2025["Team A Win"]
X.head()

,Tournament,Stage,Match Type,Map,Team A,Team B
0,Valorant Champions 2025,Group Stage,Opening (A),Bind,Paper Rex,Xi Lai Gaming
1,Valorant Champions 2025,Group Stage,Opening (A),Sunset,Paper Rex,Xi Lai Gaming
2,Valorant Champions 2025,Group Stage,Opening (A),Corrode,GIANTX,Sentinels
3,Valorant Champions 2025,Group Stage,Opening (A),Sunset,GIANTX,Sentinels
4,Valorant Champions 2025,Group Stage,Opening (A),Haven,GIANTX,Sentinels

In [37]:
from sklearn.model_selection import GroupShuffleSplit

splitter = GroupShuffleSplit(
    n_splits=1,
    test_size=0.2,
    random_state=42
)

train_idx, test_idx = next(
    splitter.split(X, y, groups=df_scores_2025["Match Name"])
)

X_train = X.iloc[train_idx]
X_test = X.iloc[test_idx]

y_train = y.iloc[train_idx]
y_test = y.iloc[test_idx]

X_train.shape, X_test.shape

((1017, 6), (260, 6))

In [38]:
from sklearn.pipeline import make_pipeline
from sklearn.preprocessing import OneHotEncoder
from sklearn.linear_model import LogisticRegression

model = make_pipeline(
    OneHotEncoder(handle_unknown="ignore"),
    LogisticRegression(max_iter=1000)
)

model.fit(X_train, y_train)

Pipeline(steps=[('onehotencoder', OneHotEncoder(handle_unknown='ignore')),
                ('logisticregression', LogisticRegression(max_iter=1000))])

In [39]:
from sklearn.metrics import accuracy_score

y_pred = model.predict(X_test)

accuracy_score(y_test, y_pred)

0.5115384615384615

In [40]:
from sklearn.metrics import classification_report

print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.48      0.57      0.52       121
           1       0.55      0.46      0.50       139

    accuracy                           0.51       260
   macro avg       0.52      0.52      0.51       260
weighted avg       0.52      0.51      0.51       260

In [41]:
df_overview_2025 = pd.read_csv("overview.csv")
df_overview_2025.shape

(53226, 21)

In [42]:
df_overview_2025.head()

,Tournament,Stage,Match Type,Match Name,Map,Player,Team,Agents,Rating,Average Combat Score,...,Deaths,Assists,Kills - Deaths (KD),"Kill, Assist, Trade, Survive %",Average Damage Per Round,Headshot %,First Kills,First Deaths,Kills - Deaths (FKD),Side
0,Valorant Champions 2025,Group Stage,Opening (A),Paper Rex vs Xi Lai Gaming,Bind,something,Paper Rex,yoru,1.63,258.0,...,12.0,12.0,9.0,91%,167.0,15%,4.0,0.0,4.0,both
1,Valorant Champions 2025,Group Stage,Opening (A),Paper Rex vs Xi Lai Gaming,Bind,something,Paper Rex,yoru,1.33,199.0,...,5.0,6.0,2.0,100%,137.0,16%,1.0,0.0,1.0,attack
2,Valorant Champions 2025,Group Stage,Opening (A),Paper Rex vs Xi Lai Gaming,Bind,something,Paper Rex,yoru,1.88,308.0,...,7.0,6.0,7.0,83%,192.0,13%,3.0,0.0,3.0,defend
3,Valorant Champions 2025,Group Stage,Opening (A),Paper Rex vs Xi Lai Gaming,Bind,Jinggg,Paper Rex,raze,1.52,315.0,...,14.0,7.0,10.0,82%,207.0,18%,5.0,2.0,3.0,both
4,Valorant Champions 2025,Group Stage,Opening (A),Paper Rex vs Xi Lai Gaming,Bind,Jinggg,Paper Rex,raze,1.11,239.0,...,7.0,2.0,1.0,80%,148.0,13%,3.0,2.0,1.0,attack

In [44]:
df_overview_2025.columns.tolist()

['Tournament',
 'Stage',
 'Match Type',
 'Match Name',
 'Map',
 'Player',
 'Team',
 'Agents',
 'Rating',
 'Average Combat Score',
 'Kills',
 'Deaths',
 'Assists',
 'Kills - Deaths (KD)',
 'Kill, Assist, Trade, Survive %',
 'Average Damage Per Round',
 'Headshot %',
 'First Kills',
 'First Deaths',
 'Kills - Deaths (FKD)',
 'Side']

In [45]:
df_overview_2025[["Match Name", "Map", "Player", "Team", "Agents"]].head(10)

                   Match Name   Map     Player       Team     Agents
0  Paper Rex vs Xi Lai Gaming  Bind  something  Paper Rex       yoru
1  Paper Rex vs Xi Lai Gaming  Bind  something  Paper Rex       yoru
2  Paper Rex vs Xi Lai Gaming  Bind  something  Paper Rex       yoru
3  Paper Rex vs Xi Lai Gaming  Bind     Jinggg  Paper Rex       raze
4  Paper Rex vs Xi Lai Gaming  Bind     Jinggg  Paper Rex       raze
5  Paper Rex vs Xi Lai Gaming  Bind     Jinggg  Paper Rex       raze
6  Paper Rex vs Xi Lai Gaming  Bind   f0rsakeN  Paper Rex  brimstone
7  Paper Rex vs Xi Lai Gaming  Bind   f0rsakeN  Paper Rex  brimstone
8  Paper Rex vs Xi Lai Gaming  Bind   f0rsakeN  Paper Rex  brimstone
9  Paper Rex vs Xi Lai Gaming  Bind      d4v41  Paper Rex      viper

In [46]:
df_overview_2025["Side"].value_counts()

Side
both      17742
attack    17742
defend    17742
Name: count, dtype: int64

In [47]:
df_agents_2025 = df_overview_2025[
    df_overview_2025["Side"] == "both"
][["Match Name", "Map", "Team", "Player", "Agents"]].copy()

df_agents_2025.shape

(17742, 5)

In [49]:
df_agents_2025.groupby(
    ["Match Name", "Map", "Team"]
).size().value_counts().head()

5     2550
10     396
15      60
20       6
6        2
Name: count, dtype: int64

In [50]:
df_agents_2025 = df_overview_2025[
    df_overview_2025["Side"] == "both"
][["Tournament", "Stage", "Match Type", "Match Name",
   "Map", "Team", "Player", "Agents"]].copy()

df_agents_2025.groupby(
    ["Tournament", "Stage", "Match Type", "Match Name", "Map", "Team"]
).size().value_counts().sort_index()

5    3546
6       2
Name: count, dtype: int64

In [51]:
group_cols = [
    "Tournament", "Stage", "Match Type",
    "Match Name", "Map", "Team"
]

team_map_counts = df_agents_2025.groupby(group_cols).size()

team_map_counts[team_map_counts != 5]

Tournament                     Stage        Match Type     Match Name                Map       Team
Valorant Masters Toronto 2025  Swiss Stage  Round 2 (0-1)  Team Liquid vs MIBR       All Maps  Team Liquid    6
                                            Round 3 (1-1)  Paper Rex vs Team Liquid  All Maps  Team Liquid    6
dtype: int64

In [52]:
df_agents_2025 = df_agents_2025[
    df_agents_2025["Map"] != "All Maps"
].copy()

df_agents_2025.shape

(12760, 8)

In [53]:
team_agents_2025 = (
    df_agents_2025.groupby(
        ["Tournament", "Stage", "Match Name", "Map", "Team"]
    )["Agents"]
    .agg(lambda agents: ", ".join(sorted(agents)))
    .reset_index()
)

team_agents_2025.head()

,Tournament,Stage,Match Name,Map,Team,Agents
0,VCT 2025: Americas Kickoff,Main Event,100 Thieves vs NRG,Bind,100 Thieves,"brimstone, fade, gekko, raze, viper"
1,VCT 2025: Americas Kickoff,Main Event,100 Thieves vs NRG,Bind,Mega Minors,"brimstone, fade, kayo, raze, viper"
2,VCT 2025: Americas Kickoff,Main Event,100 Thieves vs NRG,Lotus,100 Thieves,"breach, clove, fade, neon, omen"
3,VCT 2025: Americas Kickoff,Main Event,100 Thieves vs NRG,Lotus,Mega Minors,"breach, omen, raze, tejo, vyse"
4,VCT 2025: Americas Kickoff,Main Event,100 Thieves vs NRG,Pearl,100 Thieves,"astra, fade, jett, kayo, vyse"

In [54]:
score_maps = df_scores_2025[
    ["Match Name", "Map"]
].drop_duplicates()

agent_maps = df_agents_2025[
    ["Match Name", "Map"]
].drop_duplicates()

score_maps.merge(
    agent_maps,
    on=["Match Name", "Map"]
).shape

(1152, 2)

In [55]:
match_keys = ["Tournament", "Stage", "Match Type", "Match Name", "Map"]
score_maps = df_scores_2025[match_keys].drop_duplicates()
agent_maps = df_agents_2025[match_keys].drop_duplicates()
score_maps.merge(agent_maps,on=match_keys).shape

(1276, 5)

In [56]:
match_keys = [
    "Tournament", "Stage", "Match Type", "Match Name", "Map"
]

team_agents_2025 = (
    df_agents_2025.groupby(match_keys + ["Team"])["Agents"]
    .agg(lambda agents: ", ".join(sorted(agents)))
    .reset_index()
)

team_agents_2025.head()

,Tournament,Stage,Match Type,Match Name,Map,Team,Agents
0,VCT 2025: Americas Kickoff,Main Event,Grand Final,G2 Esports vs Sentinels,Abyss,G2 Esports,"astra, breach, chamber, sova, yoru"
1,VCT 2025: Americas Kickoff,Main Event,Grand Final,G2 Esports vs Sentinels,Abyss,Sentinels,"astra, jett, kayo, omen, tejo"
2,VCT 2025: Americas Kickoff,Main Event,Grand Final,G2 Esports vs Sentinels,Fracture,G2 Esports,"breach, brimstone, raze, tejo, vyse"
3,VCT 2025: Americas Kickoff,Main Event,Grand Final,G2 Esports vs Sentinels,Fracture,Sentinels,"breach, brimstone, tejo, vyse, yoru"
4,VCT 2025: Americas Kickoff,Main Event,Grand Final,G2 Esports vs Sentinels,Haven,G2 Esports,"astra, breach, tejo, vyse, yoru"

In [57]:
team_a_agents = team_agents_2025.rename(
    columns={"Team": "Team A", "Agents": "Team A Agents"}
)

team_b_agents = team_agents_2025.rename(
    columns={"Team": "Team B", "Agents": "Team B Agents"}
)

df_model_2025 = df_scores_2025.merge(
    team_a_agents,
    on=match_keys + ["Team A"],
    how="left"
).merge(
    team_b_agents,
    on=match_keys + ["Team B"],
    how="left"
)

df_model_2025.shape

(1277, 20)